In [1]:
import pandas as pd

comments = pd.read_csv(
    "../data/raw/kaggle_RC_2019-05.csv"
)

print("Shape:", comments.shape)
print("\nColumns:")
print(comments.columns.tolist())

display(comments.head())

Shape: (1000000, 4)

Columns:
['subreddit', 'body', 'controversiality', 'score']

,subreddit,body,controversiality,score
0,gameofthrones,Your submission has been automatically removed...,0,1
1,aww,"Dont squeeze her with you massive hand, you me...",0,19
2,gaming,It's pretty well known and it was a paid produ...,0,3
3,news,You know we have laws against that currently c...,0,10
4,politics,"Yes, there is a difference between gentle supp...",0,1

In [2]:
comments.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 4 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   subreddit         1000000 non-null  str
 1   body              1000000 non-null  str
 2   controversiality  1000000 non-null  int64
 3   score             1000000 non-null  int64
dtypes: int64(2), str(2)
memory usage: 30.5 MB

In [3]:
jokes = pd.read_csv(
    "../data/raw/one-million-reddit-jokes.csv"
)

print("Shape:", jokes.shape)
print("\nColumns:")
print(jokes.columns.tolist())

display(jokes.head())

Shape: (1000000, 12)

Columns:
['type', 'id', 'subreddit.id', 'subreddit.name', 'subreddit.nsfw', 'created_utc', 'permalink', 'domain', 'url', 'selftext', 'title', 'score']

,type,id,subreddit.id,subreddit.name,subreddit.nsfw,created_utc,permalink,domain,url,selftext,title,score
0,post,ftbp1i,2qh72,jokes,False,1585785543,https://old.reddit.com/r/Jokes/comments/ftbp1i...,self.jokes,NaN,My corona is covered with foreskin so it is no...,I am soooo glad I'm not circumcised!,2
1,post,ftboup,2qh72,jokes,False,1585785522,https://old.reddit.com/r/Jokes/comments/ftboup...,self.jokes,NaN,It's called Google Sheets.,Did you know Google now has a platform for rec...,9
2,post,ftbopj,2qh72,jokes,False,1585785508,https://old.reddit.com/r/Jokes/comments/ftbopj...,self.jokes,NaN,The vacuum doesn't snore after sex.\n\n&amp;#x...,What is the difference between my wife and my ...,15
3,post,ftbnxh,2qh72,jokes,False,1585785428,https://old.reddit.com/r/Jokes/comments/ftbnxh...,self.jokes,NaN,[removed],My last joke for now.,9
4,post,ftbjpg,2qh72,jokes,False,1585785009,https://old.reddit.com/r/Jokes/comments/ftbjpg...,self.jokes,NaN,[removed],The Nintendo 64 turns 18 this week...,134

In [4]:
jokes.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   type            1000000 non-null  str
 1   id              1000000 non-null  str
 2   subreddit.id    1000000 non-null  str
 3   subreddit.name  1000000 non-null  str
 4   subreddit.nsfw  1000000 non-null  bool
 5   created_utc     1000000 non-null  int64
 6   permalink       1000000 non-null  str
 7   domain          1000000 non-null  str
 8   url             4472 non-null     str
 9   selftext        995485 non-null   str
 10  title           1000000 non-null  str
 11  score           1000000 non-null  int64
dtypes: bool(1), int64(2), str(9)
memory usage: 84.9 MB